language: go
go:
  - 1.10.x
script:
  - cd main && time go run wc.go master sequential pg-*.txt && cd .. 
  - cd mapreduce && go test -run Sequential
  - cd mapreduce && go test -race -run TestParallel && cd ..
  - cd mapreduce && go test -race -run Failure
notifications:
  email: false
